arch:
    type: TransformerVAE
    args:
        output_emotion_dim: 25
        output_3dmm_dim: 58
        
        depth: 4
        seq_len: 750
        
        coeff_3dmm: 58
        emotion: 25
        feature_dim: 128
        device: 'cuda'

loss:
    type: Transvae_Loss
    args: 
        w_emo: 10
        w_coeff: 10

optimizer:
    lr: 0.0005
    weight_decay: 5e-4

trainer:
    epochs: 200
    resume: 
    out_dir: ./results
    save_period: 20
    val_period: 20

dataset:
    dataset_path: /public_bme/data/v-lijm/REACT_2024
    split: train

    img_size: 256
    crop_size: 224
    clip_length: 750

    batch_size: 16
    shuffle: True
    num_workers: 16

validation_dataset:
    dataset_path: /public_bme/data/v-lijm/REACT_2024
    split: val

    img_size: 256
    crop_size: 224
    clip_length: 750

    batch_size: 16
    shuffle: False
    num_workers: 16

test_dataset:
    dataset_path: ./data
    split: test

    img_size: 256
    crop_size: 224
    clip_length: 750

    batch_size: 16
    shuffle: False
    num_workers: 8